### ISSUE TITLE
Delete labs from your github profile

### ISSUE THREAD

**Issue by CalculusEnjoyer** [NikitaMasych/ACS-Lab2#1]
Why have you put some univer labs in ur github profile? that is so cringe, make them private again

**Comment by NikitaMasych** [comment]
I revel in the immaculate chaos unleashed when humanity devours itself, eager to condemn one another over the theft of hollow creations. Yet, like marionettes in some dystopian theatre, these trivial pursuits remain suspended, manipulated by unseen puppeteers.
